
export const actionTypes = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    UPDATE_QUANTITY: "UPDATE_QUANTITY",
    ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
    UPDATE_PRODUCT_LIST: "UPDATE_PRODUCT_LIST",
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    USER_REGISTER: "USER_REGISTER",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",    
    DELETE_USER: "DELETE_USER",
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    SELECT_SUBCATEGORY: 'SELECT_SUBCATEGORY',
    SET_PRICE_SORT: 'SET_PRICE_SORT',
    SELECT_COLOR: 'SELECT_COLOR',
    SELECT_SIZE: 'SELECT_SIZE',
    SET_ALPHABETICAL_SORT: 'SET_ALPHABETICAL_SORT',
    SET_POPULAR_SORT: 'SET_POPULAR_SORT',
    SET_NEWEST_SORT: 'SET_NEWEST_SORT',
    CHANGE_PAGE: 'CHANGE_PAGE', 
  };
  

