
export const actionTypes = {
    AGREGAR_AL_CARRITO: "AGREGAR_AL_CARRITO",
    REMOVER_DEL_CARRITO: "REMOVER_DEL_CARRITO",
    ACTUALIZAR_CANTIDAD: "ACTUALIZAR_CANTIDAD",
    AGREGAR_A_FAVORITOS: "AGREGAR_A_FAVORITOS",
    ACTUALIZAR_LISTA_PRODUCTOS: "ACTUALIZAR_LISTA_PRODUCTOS",
    INICIAR_SESION: "INICIAR_SESION",
    CERRAR_SESION: "CERRAR_SESION",
    REGISTRAR_USUARIO: "REGISTRAR_USUARIO",
    ACTUALIZAR_PERFIL_USUARIO: "ACTUALIZAR_PERFIL_USUARIO",    
    ELIMINAR_USUARIO: "ELIMINAR_USUARIO",
};

